--Scenario: The company needs to analyze trips that are scheduled within a specific time frame. They are particularly interested in trips that have a significant number of travelers and are associated with transportation modes capable of accommodating more than five passengers. This analysis will help in understanding trip popularity and revenue generation.

--Purpose: The primary aim is to gather insights into trip scheduling, traveler participation, and revenue generation. This information is essential for operational planning, marketing strategies, and financial analysis.

--Use Case:
--Operational Planning: By knowing the number of travelers for each trip within a specific date range, the company can better allocate resources, such as guides and transportation.
--Marketing Strategies: Identifying popular trips can help in planning future marketing campaigns and promotions.
--Financial Analysis: Understanding the total revenue generated by transportation modes helps in evaluating the financial performance of different trips.

SELECT 
    t.name AS TripName, 
    t.trip_date, 
    COUNT(tl.id_travels) AS NumberOfTravelers
FROM 
    trip t
JOIN 
    travelers_list tl ON t.id_trip = tl.id_trip
WHERE 
    t.trip_date BETWEEN TO_DATE('&<name = "start Date" list= "select distinct trip_date from trip ORDER BY TRIP_DATE">', 'DD/MM/YYYY') AND TO_DATE('&<name = "end Date" list= "select distinct trip_date from trip ORDER BY TRIP_DATE">','DD/MM/YYYY')
GROUP BY 
    t.name, t.trip_date
ORDER BY 
    t.trip_date;
