--Description/Story
--Scenario: The company wants to analyze driver performance and trip profitability on a monthly basis. By focusing on the number of travelers and total revenue, they aim to identify which drivers and transportation methods are most effective and profitable.

--Purpose: The primary aim is to provide insights into the performance of drivers based on the number of travelers they transport and the revenue generated from their trips. This helps in understanding which drivers are handling more travelers than average and which transportation methods are more profitable.

--Use Case:
--Operations Team: They can use this information to optimize driver assignments and ensure that high-performing drivers are utilized effectively.
--Financial Team: Understanding the total revenue generated by each transportation method helps in financial planning and identifying profitable routes.
--Human Resources: This data can be used to reward high-performing drivers and provide additional training or support to those who are underperforming.

SELECT 
    t.driver AS DriverName, 
    COUNT(tr.id_travels) AS TotalTravelers, 
    EXTRACT(MONTH FROM tr.trip_date) AS TravelMonth,
    (SELECT SUM(price) FROM trip WHERE id_transportation = t.id_transportation) AS TotalRevenue
FROM 
    transportation t
JOIN 
    trip tr ON t.id_transportation = tr.id_transportation
JOIN 
    travelers_list tl ON tr.id_trip = tl.id_trip
GROUP BY 
    t.driver, EXTRACT(MONTH FROM tr.trip_date)
HAVING 
    COUNT(tr.id_travels) > (SELECT AVG(count) FROM 
        (SELECT COUNT(tl.id_travels) AS count 
         FROM travelers_list tl 
         GROUP BY tl.id_trip))
ORDER BY 
    TravelMonth ASC;
